
- name: Increase Vol Size
  block:
    - name: Create log file
      file:
        path: "/tmp/{{vol_name}}_{{ansible_date_time.date}}.log"
        state: touch

    - name: Fetch number of lines from log file
      slurp:
        src: "/tmp/{{vol_name}}_{{ansible_date_time.date}}.log"
      register: log_file

    - name: Store count in varibale increased_count
      set_fact:
        increased_count: "{{ (log_file.content | b64decode).splitlines() | length }}"

    - debug:
        msg: "Number of times already incremented today: {{ increased_count }}"

    - name: Increse size
      na_ontap_volume:
        state: present
        name: {{ volume_ name }}
        aggregate_name: {{ aggr_name }}
        size: {{ total_vol_size + total_vol_size * 0.1 }}
        size_unit: bytes
        vserver: {{ vserver_name }}
        wait_for_completion: True
        comment: ansible increased size
      register: vol_increase_op
      when:
        - increased_count|int < 3    

    - name: Update log file when expansion is sucessfull
      lineinfile:
        path: "/tmp/{{vol_name}}_{{ansible_date_time.date}}.log"
        line: "{{ lookup('pipe','date +%Y-%m-%d-%H-%M-%S') }} {{ expansion_status }} {{ vol_name }}" 
      when: 
        - vol_increase_op.stdout.status == "Success"

    - debug:
        msg: "Increase volume task Failed"
      when:
        - vol_increase_op.stdout.status != "Success"