- hosts: localhost
  gather_facts: false
  vars:
    input: &input
      hostname:       "192.168.64.130"
      username:       "admin"
      password:       "netapp123"
      https:          true
      validate_certs: false
    volume_name: "myvol2"
    owning_vserver_uuid: "f1750b57-dae5-11ec-ab29-000c29386da9"
  collections:
    - netapp.ontap

  tasks:  
  - name: Get Ontap volume Info
    na_ontap_info:
      <<: *input  
      state: info
      gather_subset:
        - volume_info
      query:
        volume-attributes:
          volume-id-attributes:
            name: "{{ volume_name }}"
            owning-vserver-uuid: "{{ owning_vserver_uuid }}"
          volume-state-attributes:
            state: online
      desired_attributes:
        volume-attributes:
          volume-space-attributes:
            filesystem-size:
            size-total:
            percentage-size-used:
          volume-id-attributes:
            aggr-list:
          volume-state-attributes:
            state:
    register: netapp

  - name: run ontap info module for aggregate module, requesting specific fields
    na_ontap_info:
      <<: *input  
      gather_subset: aggregate_info
      query:
        aggregate-name: {{ netapp.ontap_info.volume_info.volume_id_attributes.aggr_list.aggr_name }}
      desired_attributes:
        aggr-space-attributes:
      use_native_zapi_tags: true
      register: ontap_agginfo

  - debug: var=ontap_agginfo

  - debug: var=netapp

  - name: Print volume details
    debug:
      msg:
        - "SVM:       {{ netapp.ontap_info.volume_info[item].volume_id_attributes.owning_vserver_name }}"
        - "Name:      {{ netapp.ontap_info.volume_info[item].volume_id_attributes.name }}"
        - "Size:      {{ netapp.ontap_info.volume_info[item].volume_space_attributes.size_total }}"
        - "Used:      {{ netapp.ontap_info.volume_info[item].volume_space_attributes.percentage_size_used }}"
    with_items:
      "{{ netapp.ontap_info.volume_info }}"

  - set_fact:
      Used_Size: "{{ netapp.ontap_info.volume_info.volume_space_attributes.size_used }}"

  - name: Prevalidate usage percentage
    block:
      - set_fact:
          precheck_status: "Pass"  
        when: Used_Size|int >= 90
      - set_fact:
          precheck_status: "Pass"  
        when: Used_Size|int <= 90

  - debug: var=precheck_status
  
  - name: Notify after precheck
    debug:
      msg: "Passed test"
    when: precheck_status == "Pass"