---

- name: Get Vol info
  include_tasks: gather_vol_info.yaml  

- name: Prevalidate usage percentage
  block:
    - set_fact:
        precheck_status: "Pass"  
      when: 
         - used_size|int >= 90
         - aggr_per_used|int < 90
         - '"{{vol_type}}" = "rw"'
         - '"k8" not in {{ vserver_name }}'
    - set_fact:
        precheck_status: "Fail"  
      when: 
         - used_size|int <= 90 or aggr_per_used|int >= 90

- debug: var=precheck_status

- name: Get Vol info
  include_tasks: get_contacts.yaml  

- name: Get the num of times vol increased in last 24hr
  postgresql_query:
    db: "{{ vol_autosize_db_name }}"
    login_host: "{{ psql_host }}"
    login_user: "{{ psql_user }}"
    login_password: "{{ psql_pass }}"        
    query: SELECt COUNT(*) FROM {{ vol_autosize_table_name }}  WHERE timestamp = "{{ ansible_date_time.date }}" AND volname = "{{vol_name}}" AND cluster = "{{ cluster }}"
  register: todays_inc_count

- debug: var=todays_inc_count

- name: Increase Vol Size
  block:
    - name: Increase Vol size
      include_tasks: increase_size.yaml
#      until: app_status.json.status == "READY"
#      retries: 3
#      delay: 5
#      register: vol_increase_op

    - name: Check used_size after increase
      include_tasks: gather_vol_info.yaml

    - name: Increase Vol size 2nd time when used % is still is not below threshold
      include_tasks: increase_size.yaml
      register: vol_inc2_op
      when:
        - used_size|int >= 93

    - name: Check used_size after increase
      include_tasks: gather_vol_info.yaml
      when:
        - vol_inc2_op.changed|bool

    - name: Increase Vol size 3nd time when used % is still is not below threshold
      include_tasks: increase_size.yaml
      register: vol_inc3_op
      when:
        - used_size|int >= 93

    - name: Check used_size after increase
      include_tasks: gather_vol_info.yaml
      when:
        - vol_inc3_op.changed|bool
  register: vol_increase_op
  when:
    - todays_inc_count|int < 3
    - precheck_status == "Pass"

- name: Notify after precheck
  include_tasks: notify.yaml
  vars:
    subject: "{{ vol_name }} increase Failed"
    message: "{{ vol_name }} used size is {{ vol_used_percent }}"
    facts: '{"volume": "{{ vol_name }}"}'
  when: 
    - not vol_increase_op.changed|bool
    - used_size|int >= 93

- name: Save vol info in psql db after increase sucessful
  postgresql_query:
    db: "{{ vol_autosize_db_name }}"
    login_host: "{{ psql_host }}"
    login_user: "{{ psql_user }}"
    login_password: "{{ psql_pass }}"        
    query: INSERT INTO {{ vol_autosize_table_name }} (timestamp, volname, cluster, volsvm, voltype, volsize, volusedpercent, increasedsize, contacts) VALUES (%s, %s, %s,%s, %s, %s, %s, %s, %s)
    positional_args:
      - "{{ ansible_date_time.date }}"
      - "{{ vol_name }}"
      - "{{ vol_svm }}"
      - "{{ vol_type }}"
      - "{{ vol_size }}"
      - "{{ vol_used_percent }}"
      - "{{ increasedsize }}"
      - "{{ increased }}"
      - "{{ contacts }}"
  when: 
    - vol_increase_op.changed|bool 
    - used_size|int < 93